### sign up ###
POST http://localhost:3000/auth/signUp
Content-Type: application/json

{
    "name": "jose",
    "email": "jose@test.com",
    "password": "123"
}

### log in ###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "jose@test.com",
    "password": "123"
}

### get  news ###
GET http://localhost:3000/news?filter=OpenIA
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiam9zZSIsImVtYWlsIjoiam9zZUB0ZXN0LmNvbSIsImlhdCI6MTcwOTgzOTQ0OH0.gis0i0ClxFpmMDNIgu7fO12tP0etVjxdniZM1jLXLQc

